import { Box, Button, Center, ChakraProvider, HStack, Stack } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { CreateForm } from 'src/features/components/form'
import { ConnectedTop } from 'src/features/components/home'

declare global {
  interface Window {
    ethereum: any
  }
}

const Home: NextPage = () => {
  // const [isConnected, setIsConnected] = useState(false);
  // const connectWallet = async () => {
  //   if (!window.ethereum)
  //     return;
  //   const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' })
  //   console.log(accounts[0]);
  //   setIsConnected(true);
  // }

  if (true) {
    return (
      <div>
        {/* <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head> */}

        <main>
          <ChakraProvider>
            <ConnectedTop />
          </ChakraProvider>
        </main>

        {/* <footer className={styles.footer}>
          <a
            href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            target='_blank'
            rel='noopener noreferrer'
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
            </span>
          </a>
        </footer> */}
      </div>
    )
  }
  //   else {
  //   return (
  //     <div>
  //       <main>
  //         <ChakraProvider>
  //           <Center>
  //             <Button
  //               onClick={connectWallet}
  //             >
  //               Connect
  //             </Button>
  //           </Center>
  //         </ChakraProvider>
  //       </main>
  //     </div>
  //   )
  // }
}

export default Home
